CREATE USER customer WITH PASSWORD 'customer_pass';
GRANT CONNECT ON DATABASE orders_db TO customer;
GRANT USAGE ON SCHEMA public TO customer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO customer;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO customer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO customer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE ON SEQUENCES TO customer;